name: Check formatting; Run './Scripts/format.sh' if this fails.

on:
  pull_request:
    branches: [main]

jobs:
  check:
    name: "check-formatted"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install SwiftFormat
        run: |
        NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew install swiftformat
      - name: Check formatting
        run: LINT=1 ./Scripts/format.sh
