name: Lint

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches-ignore:
      - 'gh-pages'
  workflow_dispatch:

jobs:
  swift-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
